protected/models/Module.php
<?php

class Module extends CActiveRecord {

  public static function model($className = __CLASS__) {
    return parent::model($className);
  }

  public function tableName() {
    return 'modules';
  }

  public function search() {
    $criteria = new CDbCriteria;
    return new CActiveDataProvider($this, array(
                'criteria' => $criteria,
            ));
  }

  public function getController() {
    switch ($this->name) {
      case 'Articles':
      case 'Article':
        return 'article';
        break;
      case 'Links':
        return 'link';
        break;
      case 'Newsletter':
        return 'newsletter';
        break;
      case 'Newsletters':
        return 'newsletter';
        break;
      case 'Banners':
        return 'banner';
        break;
      case 'Pages':
        return 'page';
        break;
      case 'Gallery':
        return 'gallery';
        break;
      case 'Multimedia':
        return 'multimedia';
        break;
      default:
        return 'Nierozpoznany Controller';
        break;
    }
  }

  public function getTranslatedName() {
    switch ($this->name) {
      case 'Articles':
        return 'Artykuły';
        break;
      case 'Article':
        return 'Artykuł';
        break;
      case 'Links':
        return 'Linki';
        break;
      case 'Newsletter':
        return 'Newsletter';
        break;
      case 'Newsletters':
        return 'Newsletter';
        break;
      case 'Banners':
        return 'Banery';
        break;
      case 'Pages':
        return 'Podstrona';
        break;
      case 'Gallery':
        return 'Galeria';
        break;
      default:
        return 'Nierozpoznany';
        break;
    }
  }

  static public function getModuleId($name) {
    $module = self::model()->find('name=:name', array(':name' => $name));
    if ($module)
      return $module->id;
    else
      throw new CHttpException(404, 'Module not exist.');
  }

  public function getSubmenu($page_id) {
    switch ($this->name) {
      case 'Articles':
      case 'Article':
        return array(
            array(
                'label' => Yii::t('cms', 'Lista artykułów'),
                'url' => Yii::app()->createUrl('article/index', array('page_id' => $page_id)),
                'active' => (getCurrentUrl() == Yii::app()->createUrl('article/index', array('page_id' => $page_id))) ? true : false
            ),
            array(
                'label' => Yii::t('cms', 'Dodaj artykuł'),
                'url' => Yii::app()->createUrl('article/create', array('page_id' => $page_id)),
                'active' => (getCurrentUrl() == Yii::app()->createUrl('article/create', array('page_id' => $page_id))) ? true : false
            ),
            array(
                'label' => Yii::t('cms', 'Edycja strony głównej'),
                'url' => Yii::app()->createUrl('page/edit', array('id' => $page_id)),
                'active' => (Yii::app()->Controller->id == 'page') ? true : false,
                'visible'=>Yii::app()->user->checkAccess('Page:Edit',array('id'=>$page_id))
            ),
        );
        break;
      case 'Gallery':
        return array(
            array(
                'label' => Yii::t('cms', 'Lista elementów'),
                'url' => Yii::app()->createUrl('gallery/index', array('page_id' => $page_id)),
                'active' => (getCurrentUrl() == Yii::app()->createUrl('gallery/index', array('page_id' => $page_id))) ? true : false
            ),
            array(
                'label' => Yii::t('cms', 'Dodaj element'),
                'url' => Yii::app()->createUrl('gallery/create', array('page_id' => $page_id)),
                'active' => (getCurrentUrl() == Yii::app()->createUrl('gallery/create', array('page_id' => $page_id))) ? true : false
            ),
            array(
                'label' => Yii::t('cms', 'Edycja strony głównej'),
                'url' => Yii::app()->createUrl('page/edit', array('id' => $page_id)),
                'active' => (Yii::app()->Controller->id == 'page') ? true : false,
            ),
        );
        break;

      default:
        break;
    }
  }

}

protected/controllers/LinkController.php
<?php

class LinkController extends Controller {

  public $layout = '//layouts/column2';
  public $menu2;
  public $page_id;

  public function filters() {
    return array(
        'accessControl',
    );
  }

  public function accessRules() {
    return array(
        array('allow',
            'roles'=>array('CmsUser')
        ),
        array('deny',
            'users' => array('*'),
        ),
    );
  }

  public function actionIndex($page_id, $mode = 'existing') {
    $this->page_id = $page_id;
    $page = Page::model()->findByPk($page_id);

    $this->setPageTitle(Yii::t('cms', 'Lista odnośników/linków'));
    $link = new Link();
    $link->page_id = isset($_GET['Link']) ? $_GET['Link']['page_id'] : $page->id;

    $pageIds = Page::getTreeIds($page->id, false);

    $this->render('index', array(
        'page' => $page,
        'link' => $link,
        'pageIds' => $pageIds,
        'mode' => $mode
    ));
  }

  public function actionAssignPageListing() {
    $page = new Page();
    if (isset($_GET['Page']))
      $page->setAttributes($_GET['Page']);
    $this->renderPartial('AssignPageListing', array(
        'page' => $page
            ), false, true);
  }

  public function actionAssignArticleListing() {
    $page = Page::model()->findByPk(1);
    $this->page_id = $page->id;
    $articleTranslation = new ArticleTranslation('search');
    $articleTranslation->unsetAttributes();
    if (isset($_GET['ArticleTranslation']))
      $articleTranslation->attributes = $_GET['ArticleTranslation'];

    $article = new Article();
    $article->page_id = isset($_GET['Article']) ? $_GET['Article']['page_id'] : $page->id;

    $pageIds = Page::getTreeIds($article->page_id, false);

    $this->renderPartial('AssignArticleListing', array(
        'page' => $page,
        'articleTranslation' => $articleTranslation,
        'pageIds' => $pageIds,
        'article' => $article
            ), false, true);
  }

  public function getTabs($model) {
    $possibleTabs = array(
        'index' => array(
            'translated' => Yii::t('cms', '<-- Wróć do listy linków'),
            'url' => $this->createUrl('link/index', array('page_id' => $model->page_id)),
            'view' => 'index'),
//        'view' => array(
//            'translated' => Yii::t('cms', 'Informacje podstawowe'),
//            'url' => $this->createUrl('link/view', array('id' => $model->id)),
//            'view' => 'view'),
        'CreateRelated' => array(
            'translated' => Yii::t('cms', 'Edycja linku do istniejącej podstrony'),
            'url' => $this->createUrl('link/CreateRelated', array('page_id' => $model->page_id, 'id' => $model->id)),
            'view' => '_existing_page'),
        'files' => array(
            'translated' => Yii::t('cms', 'Obrazki i pliki'),
            'url' => $this->createUrl('link/files', array('id' => $model->id)),
            'view' => 'files'),
        'blocks' => array(
            'translated' => Yii::t('cms', 'Bloki i wystąpienia'),
            'url' => $this->createUrl('link/blocks', array('id' => $model->id)),
            'view' => 'blocks'),
    );
    $tabs = array();
    foreach ($possibleTabs as $action => $translated) {
      if (Yii::app()->getController()->action->id == $action) {
        $tabs[$action] = array(
            'title' => Yii::t('cms', $translated['translated']),
            'view' => $translated['view'],
        );
      } else {
        $tabs[$action] = array(
            'title' => Yii::t('cms', $translated['translated']),
            'url' => $translated['url'],
        );
      }
    }
    return $tabs;
  }

  public function actionView($id) {
    $link = Link::model()->findByPk($id);
    $this->page_id = $link->page->id;

    $this->render('//shared/tabs', array(
        'page' => $link->page,
        'model' => $link,
        'tabs' => $this->getTabs($link),
        'additionalParams' => array('module_id' => Link::getModuleId())
    ));
  }

  public function actionBlocks($id) {
    $link = Link::model()->findByPk($id);
    $this->setPageTitle(Yii::t('cms', 'Bloki na stronie i wystąpienia elementu'));
    $this->page_id = $link->page->id;
    $this->render('tabs', array(
        'page' => $link->page,
        'model' => $link,
        'tabs' => $this->getTabs($link),
        'additionalParams' => array('module_id' => Link::getModuleId())
    ));
  }

  public function actionFiles($id) {
    $link = Link::model()->findByPk($id);
    $this->setPageTitle(Yii::t('cms', 'Obrazki i pliki elementu'));
    $this->page_id = $link->page->id;
    $this->render('tabs', array(
        'page' => $link->page,
        'model' => $link,
        'tabs' => $this->getTabs($link),
        'additionalParams' => array('module_id' => Link::getModuleId())
    ));
  }

  public function actionCreateRelated($page_id, $id = false) {
    $page = Page::model()->findByPk($page_id);
    $this->page_id = $page->id;
    $this->setPageTitle(Yii::app()->name . ' - ' . $page->name . ' - ' . Yii::t('cms', 'Dodaj element'));
    if ($id) {
      $link = Link::model()->findByPk($id);
      $link->setScenario('createRelated');
    } else {
      $link = new Link('createRelated');
      $link->setAttribute('page_id', $page_id);
    }
    $url = new Url('create');
    $url->setAttributes(array('lang_id' => Yii::app()->params['lang']->id));
    if (Yii::app()->request->isPostRequest) {
      $transaction = Yii::app()->db->beginTransaction();
      $commit = true;
      $link->setAttributes($_POST['Link']);
      if (!$link->save()) {
        $commit = false;
      }

      if ($commit) {
        $transaction->commit();
        if ($id) {
          Yii::app()->user->setFlash('success', Yii::t('cms', 'Zmiany zostały zapisane.'));
        } else {
          Yii::app()->user->setFlash('success', Yii::t('cms', 'Nowy link został utworzony.'));
        }
        $this->redirect($this->createUrl('link/index', array('page_id' => $page->id)));
      } else {
        $transaction->rollback();
      }
    }
    if ($id) {
      $this->setPageTitle(Yii::t('cms', 'Edycja elementu'));
      $this->render('tabs', array(
          'page' => $link->page,
          'model' => $link,
          'tabs' => $this->getTabs($link),
          'additionalParams' => array('module_id' => Link::getModuleId(), 'url' => $url, 'id' => $id, 'link' => $link, 'page' => $link->page)
      ));
    } else {
      $this->setPageTitle(Yii::t('cms', 'Dodaj nowy odnośnik/link'));
      $this->render('create', array(
          'link' => $link,
          'page' => $page,
          'url' => $url,
          'id' => $id
      ));
    }
//
  }

  public function actionCreateNotRelated($page_id, $id = false) {
    $page = Page::model()->findByPk($page_id);
    $this->setPageTitle(Yii::app()->name . ' - ' . $page->name . ' - ' . Yii::t('cms', 'Dodaj element'));
    if ($id) {
      $link = Link::model()->findByPk($id);
      $link->setScenario('createNotRelated');
      $url = Url::model()->findByPk(array('element_name' => 'Link', 'element_id' => $id, 'lang_id' => Yii::app()->params['lang']->id));
    } else {
      $link = new Link('createNotRelated');
      $link->setAttribute('page_id', $page_id);
      $url = new Url('create');
      $url->setAttributes(array('lang_id' => Yii::app()->params['lang']->id));
    }

    if (Yii::app()->request->isPostRequest) {
      $transaction = Yii::app()->db->beginTransaction();
      $commit = true;
      if (!$link->save()) {
        $commit = false;
      }
      if (isset($_FILES) && $_FILES['files']['name'][0]) {
        $messagesPerFile = array();
        $messages = array('success' => array(), 'error' => array());
        foreach ($_FILES['files']['name'] as $index => $filePost) {
          $fileData = array(
              'name' => $_FILES['files']['name'][$index],
              'type' => $_FILES['files']['type'][$index],
              'tmp_name' => $_FILES['files']['tmp_name'][$index],
              'error' => $_FILES['files']['error'][$index],
              'size' => $_FILES['files']['size'][$index]
          );
          if ($id && $link->multimediaCount) {
            $messagesPerFile[] = Multimedia::uploadFile($fileData, 'Link', $link->id, $link->multimedia[0]->id);
          } else {
            $messagesPerFile[] = Multimedia::uploadFile($fileData, 'Link', $link->id);
          }
        }
        foreach ($messagesPerFile as $message)
          foreach (array('success', 'error') as $field)
            if (isset($message[$field]))
              $messages[$field][] = $message[$field];
        if (isset($messages['error']) && $messages['error'])
          $commit = false;
      }
      elseif (!$id) {
        $link->addError('related_page_id', "Obrazek nie został wgrany.");
        $commit = false;
      }
      $url->setAttributes($_POST['Url']);
      $url->setAttributes(array('element_name' => 'Link', 'element_id' => $link->id));
      if (!$url->save())
        $commit = false;

      if ($commit) {
        $transaction->commit();
        if ($id) {
          Yii::app()->user->setFlash('success', Yii::t('cms', 'Zmiany zostały zapisane.'));
          //$this->redirect($this->createUrl('link/createNotRelated', array('page_id' => $page->id,'id'=>$link->id)));
        } else {
          Yii::app()->user->setFlash('success', Yii::t('cms', 'Nowy link został utworzony.'));
        }
        $this->redirect($this->createUrl('link/index', array('page_id' => $page->id, 'mode' => 'nonexisting')));
      } else {
        $transaction->rollback();
      }
    }
    $this->render('create', array(
        'link' => $link,
        'page' => $page,
        'url' => $url,
        'id' => $id
    ));
  }

  public function actionDelete($id) {
    $link = Link::model()->findByPk($id);
    if ($link->delete()) {
      Yii::app()->user->setFlash('success', Yii::t('cms', 'Element został usunięty.'));
    }

protected/views/link/AssignArticleListing.php
<div class="form">
  <p class="note">Kliknij na podstronę do której ma kierować link.</p>
</div>
<?
$globalId = 'CreateExistingPage';
$gridId = $globalId.'PageGrid';
$gridDialogId = $gridId.'Dialog';
$gridDialogArticleId = $gridId.'ArticleDialog';
$gridFormId = $globalId.'Form';
$gridFormRelatedToId = $gridFormId.'_related_element_id';
$this->widget('zii.widgets.grid.CGridView', array(
  'id'=>$gridId,
  'dataProvider'=>$articleTranslation->search($pageIds),
  'filter'=>$articleTranslation,
  'ajaxUrl'=>$this->createUrl('link/AssignArticleListing'),
    'cssFile' => Yii::app()->theme->baseUrl.'/css/gridview/gridview.css',
  'enableSorting'=>false,
  'selectionChanged'=>'
    function(id){
      element_id=$.fn.yiiGridView.getSelection(id);
      trInst = $(\'#\'+id).find(\'tr.selected\');
      var element_name = $(trInst).children(\'td:first\').text();
      if(element_id.length>0) {
        element_id = element_id[0];
        element_id = element_id.split(\',\');
        element_id = element_id[0];
        $(\'#Link_related_module_id\').val(\''.Article::getModuleId().'\');
        $(\'#'.$gridFormRelatedToId.'\').prepend(\'<option value="\'+element_id+\'">\'+element_name+\'</option>\');
        $(\'#'.$gridFormRelatedToId.'\').val(element_id);
      }
      $(\'#'.$gridDialogArticleId.'\').dialog(\'close\');
    }',
  'columns'=>array(
      'title',
      array(
            'name' => 'parent.page_id',
            'value' => '$data->parent->page->name',
            'filter' => CHtml::dropDownList('Article[page_id]', $article->page_id, CHtml::listData(Page::model()->findAll('`id` IN (' . implode(',', Page::getTreeIds($page->id, false)) . ')'), 'id', 'name', 'parent.name')),
        ),
    ),
));?>

<?
Yii::app()->clientScript->scriptMap['jquery.js'] = false;
//Yii::app()->clientScript->scriptMap['jquery.ba-bbq.js'] = false;
?>

protected/views/link/AssignPageListing.php
<div class="form">
  <p class="note">Kliknij na podstronę do której ma kierować link.</p>
</div>
<?
$globalId = 'CreateExistingPage';
$gridId = $globalId.'PageGrid';
$gridDialogId = $gridId.'Dialog';
$gridFormId = $globalId.'Form';
$gridFormRelatedToId = $gridFormId.'_related_element_id';
$this->widget('zii.widgets.grid.CGridView', array(
  'id'=>$gridId,
  'dataProvider'=>$page->searchToLink('DataProvider'),
  'filter'=>$page,
  'ajaxUrl'=>$this->createUrl('link/AssignPageListing'),
    'cssFile' => Yii::app()->theme->baseUrl.'/css/gridview/gridview.css',
  'enableSorting'=>false,
  'selectionChanged'=>'
    function(id){
      element_id=$.fn.yiiGridView.getSelection(id);
      trInst = $(\'#\'+id).find(\'tr.selected\');
      var element_name = $(trInst).children(\'td:first\').text();
      if(element_id.length>0) {
        element_id = element_id[0];
        $(\'#Link_related_module_id\').val(\''.Page::getModuleId().'\');
        $(\'#'.$gridFormRelatedToId.'\').prepend(\'<option value="\'+element_id+\'">\'+element_name+\'</option>\');
        $(\'#'.$gridFormRelatedToId.'\').val(element_id);
      }
      $(\'#'.$gridDialogId.'\').dialog(\'close\');
    }',
  'columns'=>array(
      'name',
      array(
        'name'=>'parent_id',
        'value'=>'$data->parentName',
        'filter'=>CHtml::listData(Page::model()->findAll(Page::getTreeCriteria(true)), 'id', 'name', 'parent.name'),
      )
    ),
));?>

<?
Yii::app()->clientScript->scriptMap['jquery.js'] = false;
Yii::app()->clientScript->scriptMap['jquery.ba-bbq.js'] = false;
?>

protected/views/link/_breadcrumbs.php
<?
$parent = $page;
while($parent = $parent->parent) {
  if($parent->id>1)
    $this->breadcrumbs = array_merge($this->breadcrumbs, array(Yii::t('cms', $parent->name)=>$this->createUrl('link/index',array('page_id'=>$parent->id))));
  else break;
}
$this->breadcrumbs = array_merge($this->breadcrumbs, array(Yii::t('cms', $page->name)=>$this->createUrl('link/index',array('page_id'=>$page->id))));

?>

protected/views/link/_existing_page.php
<?
$globalId = 'CreateExistingPage';
$gridId = $globalId.'PageGrid';
$gridDialogId = $gridId.'Dialog';
$gridDialogArticleId = $gridId.'ArticleDialog';
$gridFormId = $globalId.'Form';
$gridFormRelatedToId = $gridFormId.'_related_element_id';
?>
<?
$this->beginWidget('zii.widgets.jui.CJuiDialog', array(
  'id'=>"$gridDialogId",
  'options'=>array(
      'title'=>  Yii::t('cms', 'Wybierz podstronę'),
      'autoOpen'=>false,
      'modal'=>true,
      'width'=>'800',
      'open'=>'js:function(){
          jQuery.ajax({
            "url": "'.$this->createUrl('link/AssignPageListing').'",
            "success":function(data){
              $(\'#'.$gridDialogId.'\').html($(data));
            }
          });
          return false;}',
      'buttons'=>array(
          'Anuluj'=>'js:function(){$(this).dialog(\'close\');$(\'#'.$gridFormRelatedToId.'\').val(\''.$link->related_element_id.'\');}',
      )
  ),
));
$this->endWidget('zii.widgets.jui.CJuiDialog');
?>

<?
$this->beginWidget('zii.widgets.jui.CJuiDialog', array(
  'id'=>"$gridDialogArticleId",
  'options'=>array(
      'title'=>  Yii::t('cms', 'Wybierz artykuł'),
      'autoOpen'=>false,
      'modal'=>true,
      'width'=>'800',
      'open'=>'js:function(){
          jQuery.ajax({
            "url": "'.$this->createUrl('link/AssignArticleListing').'",
            "success":function(data){
              $(\'#'.$gridDialogArticleId.'\').html($(data));
            }
          });
          return false;}',
      'buttons'=>array(
          'Anuluj'=>'js:function(){$(this).dialog(\'close\');$(\'#'.$gridFormRelatedToId.'\').val(\''.$link->related_element_id.'\');}',
      )
  ),
));
$this->endWidget('zii.widgets.jui.CJuiDialog');
?>

<div class="form">
  <?$form=$this->beginWidget('CActiveForm',array('action'=>$this->createUrl('link/createRelated',array('page_id'=>$page->id,'id'=>$id)),'htmlOptions' => array('id'=>$gridFormId,'enctype' => 'multipart/form-data'))); ?>
    <div class="row">
      <?= $form->hiddenField($link,'related_module_id')?>
      <?$id = $gridFormId.'_related_element_id'?>
      <?= CHtml::label(Yii::t('cms', 'Podstrona na którą wskazuje link'), $id)?>
      <?= CHtml::activeDropDownList($link, 'related_element_id', array($link->related_element_id=>(($link->related_element_id)? $link->module->translatedName:''),'PagePicker'=>'Kliknij aby wybrać podstronę','ArticlePicker'=>'Kliknij aby wybrać artykuł'),
              array('onclick'=>'if($(this).val()=="PagePicker"){$(\'#'.$gridDialogId.'\').dialog(\'open\');}else if($(this).val()=="ArticlePicker"){$(\'#'.$gridDialogArticleId.'\').dialog(\'open\');}','id'=>$id)) ?>
      <?php echo $form->error($link, 'related_element_id'); ?>
    </div>
    <div class="row buttons">
      <?php echo CHtml::submitButton(Yii::t('cms', 'Zapisz')); ?>
    </div>
  <?$this->endWidget();?>
</div>

protected/views/link/_listing_existing.php
<?
$this->widget('zii.widgets.grid.CGridView', array(
    'id' => 'links-grid',
    'cssFile' => Yii::app()->theme->baseUrl.'/css/gridview/gridview.css',
    'dataProvider' => $link->search($pageIds, 'existing'),
    'afterAjaxUpdate' => 'installSortable',
    'rowCssClassExpression'=>'"items_{$data->id}"',
    'columns' => array(
        gridViewsortIcon(),
        array(
            'name' => Yii::t('cms', 'Podstrona na którą wskazuje link'),
            'type' => 'raw',
            'value' => '$data->module->translatedName." - ".$data->title'
        ),
        array(
            'class' => 'SButtonColumn',
            'template' => '{status}',
            'htmlOptions'=>array('class'=>'icons'),
            'header'=>  Yii::t('cms', 'Status'),
            'buttons' => array(
                'status' => array(
                    'expressionImage'=>true,
                    'expressionLabel'=>true,
                    'label'=>'$data->getStatusExpression()',
                    'type' => 'html',
                    'url' => 'Yii::app()->createUrl("link/statusSwitch", array("id"=>$data->id))',
                    'imageUrl' => '$data->getStatusIcon()',
                    'click' => "function() {
                      $.ajax({
                        url: $(this).attr('href'),
                        success: function(data) {
                          if($(data).first('.errorSummary').length) {
                            $('#links-grid').prepend('<div class=\"form\">'+data+'</div>');
                          }
                          else {
                            $.fn.yiiGridView.update('links-grid');
                          }
                        }
                      });
                      return false;}
                      ",
                ),
            ),
        ),
        array(
            'class' => 'SButtonColumn',
            'template' => '{update}',
            'htmlOptions'=>array('class'=>'icons'),
            'header'=>  Yii::t('cms', 'Edycja'),
            'buttons' => array(
                'update' => array(
                    'label' => Yii::t('cms', 'Edytuj'),
                    'url' => 'Yii::app()->createUrl("link/CreateRelated", array("page_id"=>$data->page_id,"id"=>$data->id))',
                ),
            ),
        ),
        array(
            'class' => 'SButtonColumn',
            'template' => '{delete}',
            'htmlOptions'=>array('class'=>'icons'),
            'header'=>  Yii::t('cms', 'Usuń'),
            'buttons' => array(
                'delete' => array(
                    'label' => Yii::t('cms', 'Usuń'),
                    'url' => 'Yii::app()->createUrl("link/delete", array("id"=>$data->id))',
                ),
            ),
        ),
    ),
));
?>

protected/views/link/_listing_nonexisting.php
<?

$this->widget('zii.widgets.grid.CGridView', array(
    'id' => 'links-grid',
    'dataProvider' => $link->search($pageIds, 'nonexisting'),
    'afterAjaxUpdate' => 'installSortable',
    'rowCssClassExpression'=>'"items_{$data->id}"',
    'columns' => array(
        array(
            'name' => Yii::t('cms', 'Adres na który wskazuje link'),
            'type' => 'raw',
            'value' => '"<a href=\"".$data->defaultUrl->address."\">".$data->defaultUrl->address."</a>"'
        ),
        array(
            'name' => 'defaultUrl.blank',
            'type' => 'raw',
            'value' => '$data->defaultUrl->TranslateEnumValue(\'blank\')'
        ),
        array(
            'name' => Yii::t('cms', 'Podgląd obrazka'),
            'type' => 'raw',
            'value' => '$data->multimedia[0]->Mini'
        ),
        array(
          'name'=>'urlsLangIcons',
          'type'=>'raw',
          'filter'=>false,
        ),
        array(
            'class' => 'SButtonColumn',
            'template' => '<span style="white-space: nowrap">{status}&nbsp;&nbsp;&nbsp;{update}&nbsp;&nbsp;&nbsp;{delete}</span>',
            'buttons' => array(
                'update' => array(
                    'label' => Yii::t('cms', 'Edytuj'),
                    'url' => 'Yii::app()->createUrl("link/createNotRelated", array("id"=>$data->id,"page_id"=>$data->page_id))',
                ),
                'delete' => array(
                    'label' => Yii::t('cms', 'Usuń'),
                    'url' => 'Yii::app()->createUrl("link/delete", array("id"=>$data->id))',
                ),
                'status' => array(
                    'expressionImage'=>true,
                    'expressionLabel'=>true,
                    'label'=>'$data->getStatusExpression()',
                    'type' => 'html',
                    'url' => 'Yii::app()->createUrl("link/statusSwitch", array("id"=>$data->id))',
                    'imageUrl' => '$data->getStatusIcon()',
                    'click' => "function() {
                      $.ajax({
                        url: $(this).attr('href'),
                        success: function(data) {
                          if($(data).first('.errorSummary').length) {
                            $('#links-grid').prepend('<div class=\"form\">'+data+'</div>');
                          }
                          else {
                            $.fn.yiiGridView.update('links-grid');
                          }
                        }
                      });
                      return false;}
                      ",
                ),
            ),
        ),
    ),
));
?>

protected/views/link/blocks.php
<?Yii::app()->clientScript->registerScript('loadBlocks', 'jQuery.ajax({
  "url":"'.$this->createUrl('block/IndexByElement',array('module_id'=>$module_id,'element_id'=>$model->id)).'",
    "success":function(data){
              $(\'#BlocksListing\').html(data);
            }
})');?>
<div id="BlocksListing">
 <?= loadingString()?>
</div>

protected/views/link/files.php
<?Yii::app()->clientScript->registerScript('loadAttachments', 'jQuery.ajax({
  "url":"'.$this->createUrl('multimedia/index',array('module_id'=>$module_id,'element_id'=>$model->id,'redirectAction'=>Yii::app()->controller->getAction()->getId())).'",
    "success":function(data){
              $(\'#multimediaListing\').html(data);
            }
})');?>
<div id="multimediaListing">
  <?= loadingString()?>
</div>