protected/models/Recipient.php
<?php

class Recipient extends CActiveRecord {

  public static function model($className = __CLASS__) {
    return parent::model($className);
  }

  public function tableName() {
    return 'recipients';
  }

  public function relations() {
    return array(
        'groups' => array(self::MANY_MANY, 'Group', 'recipient_group(recipient_id, group_id)')
    );
  }

  public function rules() {
    return array(
        array('email, status', 'required'),
        array('email','email'),
        array('email','unique','caseSensitive'=>false),
        array('email, status','safe', 'on'=>'search')
    );
  }

  public function attributeLabels() {
    return array(
        'id' => 'ID',
        'email' => Yii::t('cms', 'Adres email'),
    );
  }

//  public function checkUnique($attribute,$params) {
//    $exist = Recipient::model()->find('`email`=:email',array(':email'=>$this->email));
//    if($exist) {
//      switch ($this->status) {
//        case -1:
//          $msg = Yii::t('cms', 'Podany adres e-mail już istnieje i nie został jeszcze potwierdzony.');
//          break;
//        case 0:
//          $msg = Yii::t('cms', 'Podany adres e-mail jest wypisany z listy mailingowej.');
//          break;
//        default:
//          $msg = Yii::t('cms', 'Podany adres e-mail już istnieje.');
//          break;
//      }
//    }
//    if(isset($msg)) $this->addError ('email', $msg);
//  }

  public function getEnumOptions($fieldName) {
    $values = false;
    switch ($fieldName) {
      case 'status':
        $values = array(
            -1 => Yii::t('cms', 'Niepotwierdzony'),
            0 => Yii::t('cms', 'Nieaktywny'),
            1 => Yii::t('cms', 'Aktywny'),
        );
        break;
      default:
        break;
    }
    return $values;
  }

  public function TranslateEnumValue($fieldName) {
    $values = $this->getEnumOptions($fieldName);
    if (isset($values[$this->$fieldName])) {
      return $values[$this->$fieldName];
    }
    else
      return $this->$fieldName;
  }

  public function beforeValidate() {
    if($this->getIsNewRecord()) {
      if(!isset($this->status)) $this->status = 1;
    }
    return parent::beforeValidate();
  }

  public function search($group_id = false) {
    $criteria = new CDbCriteria;
    $criteria->compare('email', $this->email, true);
    $criteria->compare('status', $this->status, true);
    if($group_id) {
      $criteria->join = 'INNER JOIN `recipient_group` `recipient_group` ON `t`.`id`=`recipient_group`.`recipient_id`';
      $criteria->compare('`recipient_group`.`group_id`', $group_id, true);
    }
    return new CActiveDataProvider($this, array(
                'criteria' => $criteria,
            ));
  }

}

protected/controllers/RecipientController.php
<?php

class RecipientController extends Controller {

  public $layout = '//layouts/column2';
  public $menu2;
  public $page_id;

  public function filters() {
    return array(
        'accessControl',
    );
  }

  public function accessRules()
	{
		return array(
			array('allow',
				'roles'=>array('CmsUser')
			),
      array('deny',
				'users'=>array('*'),
			),
		);
	}

  public function getTabs($model,$page) {
    $possibleTabs = array(
        'newsletter' => array(
            'translated' => Yii::t('cms', '<-- Wróć do listy wiadomości'),
            'url' => $this->createUrl('newsletter/index',array('page_id'=>$page->id)),
            'view' => ''),
        'index' => array(
            'translated' => Yii::t('cms', 'Lista odbiorców'),
            'url' => $this->createUrl('recipient/index', array('page_id'=>$page->id)),
            'view' => 'index'),
        'groups' => array(
            'translated' => Yii::t('cms', 'Grupy odbiorców'),
            'url' => $this->createUrl('recipient/groups', array('page_id'=>$page->id)),
            'view' => 'groups'),
        'add' => array(
            'translated' => Yii::t('cms', 'Dodaj odbiorców'),
            'url' => $this->createUrl('recipient/add', array('page_id'=>$page->id)),
            'view' => 'add'),
    );
    $tabs = array();
    foreach ($possibleTabs as $action => $translated) {
      if (Yii::app()->getController()->action->id == $action) {
        $tabs[$action] = array(
            'title' => Yii::t('cms', $translated['translated']),
            'view' => $translated['view'],
        );
      } else {
        $tabs[$action] = array(
            'title' => Yii::t('cms', $translated['translated']),
            'url' => $translated['url'],
        );
      }
    }
    return $tabs;
  }

  public function actionIndex($page_id) {
    $page = Page::model()->findByPk($page_id);
    $this->page_id = $page->id;
    $this->setPageTitle(Yii::t('cms', 'Lista wszystkich odbiorców'));
    $recipient = new Recipient('search');
    $group = new Group();
    if(isset($_GET['Recipient'])) {
      $recipient->setAttributes($_GET['Recipient']);
    }
    if(isset($_GET['Group'])) {
      $group->setAttributes($_GET['Group'],false);
    }

    $this->render('tabs', array(
        'page' => $page,
        'model' => false,
        'tabs' => $this->getTabs(false,$page),
        'additionalParams' => array('module_id' => Newsletter::getModuleId(),'recipient'=>$recipient,'group'=>$group)
    ));
  }

  public function actionGroups($page_id) {
    $page = Page::model()->findByPk($page_id);
    $this->setPageTitle(Yii::t('cms', 'Grupy odbiorców'));
    $this->page_id = $page->id;
    $group = new Group();

    $this->render('tabs', array(
        'page' => $page,
        'model' => false,
        'tabs' => $this->getTabs(false,$page),
        'additionalParams' => array('module_id' => Newsletter::getModuleId(), 'group'=>$group)
    ));
  }

  public function actionGroupEdit($id) {
    $group = Group::model()->findByPk($id);
    if(Yii::app()->request->isPostRequest) {
      $group->setAttributes($_POST['Group']);
      if($group->save()) {
        Yii::app()->user->setFlash('success', Yii::t('cms', 'Zmiany zostały zapisane.'));
        $this->refresh();
      }
    }

    $this->renderPartial('groupEdit',array('group'=>$group),false,true);
  }

  public function actionGroupAdd() {
    $group = new Group('create');
    if(isset($_POST['Group'])) {
      $group->setAttributes($_POST['Group']);
      if($group->save()) {
        Yii::app()->user->setFlash('success', Yii::t('cms', 'Dane zostały zapisane.'));
        $this->refresh();
      }
    }
    $this->renderPartial('addGroup', array(
        'group'=>$group
    ),false,true);
  }

  public function actionView($id) {
    $recipient = Recipient::model()->findByPk($id);
    if(Yii::app()->request->isPostRequest) {
      $recipient->setAttributes($_POST['Recipient']);
      $selectedGroups = isset($_POST['groups'])? $_POST['groups']:array();
      foreach(Group::model()->findAll() as $group) {
        $recipientGroupParams = array('recipient_id'=>$recipient->id,'group_id'=>$group->id);
        if(in_array($group->id, $selectedGroups)) {
          RecipientGroup::saveNew($recipientGroupParams['recipient_id'], $recipientGroupParams['group_id']);
        }
        else {
          $exist = RecipientGroup::model()->findByPk($recipientGroupParams);
          if($exist) $exist->delete();
        }
      }
      if($recipient->save()) {
        Yii::app()->user->setFlash('success', Yii::t('cms', 'Zmiany zostały zapisane.'));
        $this->refresh();
      }
    }

    $this->renderPartial('view',array('recipient'=>$recipient,'recipient_groups'=>  CHtml::listData($recipient->groups, 'id', 'id')),false,true);
  }

  public function actionAdd($page_id) {
    $page = Page::model()->findByPk($page_id);
    $this->page_id = $page->id;
    $this->setPageTitle(Yii::t('cms', 'Dodaj odbiorców'));
    $recipient = new Recipient();
    $emails = array();
    $errors = array();
    $groups = array();
    if(Yii::app()->request->isPostRequest) {
      $groups = isset($_POST['groups'])? $_POST['groups']:$groups;
      $emails = $_POST['emails'];
      preg_match_all(emailRegexp(),$emails,$matches);
      $emails = $matches[0];
      $emails = array_unique($emails);
      if(!$groups) {
        array_push($errors, Yii::t('cms', 'Wskaż do jakich grup przypisać odbiorców (musisz wskazać przynajmniej jedną grupę).'));
      }
      if(!$emails) {
        array_push($errors, Yii::t('cms', 'Podaj adresy email.'));
      }
      if(!$errors && isset($_POST['save'])) {
        $savedRecipients = array();
        $unsavedRecipients = array();
        $existingRecipients = array();
        foreach($emails as $email) {
          $recipient = Recipient::model()->find('`email`=:email',array(':email'=>$email));
          if(!$recipient) {
            $recipient = new Recipient('create');
            $recipient->setAttributes(array('email'=>$email));
            if($recipient->save()) {

              array_push($savedRecipients, $email);
            }
            else {
              array_push($unsavedRecipients, $email);
            }
          }
          else {
            array_push($existingRecipients, $email);
          }
          if(!$recipient->getErrors())
            foreach($groups as $group_id) RecipientGroup::saveNew ($recipient->id, $group_id);
        }
        Yii::app()->user->setFlash('success', Yii::t('cms', 'Liczba dodanych odbiorców: ').count($savedRecipients).'<br />'.  Yii::t('cms', 'Liczba odbiorców którzy już istnieli w systemie: ').  count($existingRecipients));
        if($unsavedRecipients)
          Yii::app()->user->setFlash('error', Yii::t('cms', 'Liczba odbiorców przy których wystąpił problem: ').count($unsavedRecipients).'<br />'.  implode(', ', $unsavedRecipients));
          $this->refresh();
      }
    }
    $this->render('tabs', array(
        'page' => $page,
        'model' => false,
        'tabs' => $this->getTabs(false,$page),
        'additionalParams' => array('module_id' => Newsletter::getModuleId(),'emails'=>  $emails,'errors'=>$errors,'groups'=>$groups)
    ));
  }

}

protected/views/recipient/_leftMenu.php
<?
$this->menu = array(
//    array(
//        'label' => Yii::t('cms', 'Stwórz nowy newsletter'),
//        'url' => $this->createUrl('newsletter/create', array('page_id' => $page->id))
//    ),
    array(
        'label' => Yii::t('cms', 'Lista wiadomości'),
        'url' => $this->createUrl('newsletter/index', array('page_id' => $page->id))
    ),
//    array(
//        'label' => Yii::t('cms', 'Zarządzaj odbiorcami'),
//        'url' => $this->createUrl('recipient/index', array('page_id' => $page->id))
//    ),
//    array(
//        'label' => Yii::t('cms', 'Edycja kategorii'),
//        'url' => $this->createUrl('page/edit', array('id' => $page->id)),
//        'visible'=>Yii::app()->user->checkAccess('Administrator')
//    ),
);
?>

protected/views/recipient/add.php
<div class="form">
  <?if($errors):?>
    <div class="<?=CHtml::$errorSummaryCss?>">
      <p><?=Yii::t('yii','Please fix the following input errors:')?></p>
      <ul>
        <?foreach($errors as $error):?>
          <li><?= $error?></li>
        <?endforeach?>
      </ul>
    </div>
  <?endif?>
  <? $form = $this->beginWidget('CActiveForm'); ?>
    <div class="row">
        <legend><?= Yii::t('cms', 'Wskaż do jakich grup zostaną dodani odbiorcy') ?></legend>
        <div id="GroupsToSelectWhileRecipientsImport"></div>
        <div style="float: left; height: 20px; width: 100%;"></div>
        <div class="button_bar">
        <div class="button_add">
        <input type="button" name="addGroup" value="Dodaj nową grupę" onclick="$('#addGroupDialog').dialog('open')" />
        </div>
        </div>
    </div>
    <div class="row">
    	<div style="float: left; height: 20px; width: 100%;"></div>
    	  <div class="note">
              <?= Yii::t('cms', 'Adresy mogą być oddzielone spacją, znakiem enter, przecinkami i wiele innych.') ?>
          </div>
        <legend><?= Yii::t('cms', 'Wprowadź adresy email.') ?></legend>

          <div style="margin-right:20px">
            <textarea cols="80" style="width: 100%" rows="20" name="emails"><?= implode(chr(13), $emails)?></textarea>
          </div>  
        <div class="button_bar">
        	<div class="button_add">
              <?php echo CHtml::submitButton(Yii::t('cms', 'Wczytaj odbiorców'),array('name'=>'refresh')); ?>
            </div>
        	<div class="button_add">
        	  <?php echo CHtml::submitButton(Yii::t('cms', 'Zapisz odbiorców'),array('name'=>'save')); ?>
     		</div>            
        </div>
    </div>
  <? $this->endWidget(); ?>
</div>

<?php
$this->beginWidget('zii.widgets.jui.CJuiDialog',array(
  'id'=>'addGroupDialog',
  'options'=>array(
      'title'=>Yii::t('cms','Dodaj grupę'),
      'autoOpen'=>false,
      'modal'=>'true',
      'width'=>'auto',
      'height'=>'auto',
      'close'=>'js:function(){reInstall()}',
      'open'=>'js:function(){
        jQuery.ajax({
          "url":"'.$this->createUrl('recipient/GroupAdd').'",
            "type":"get",
            "success":function(data){
              $(\'#addGroupDialog\').html(data);
              $(\'#Group_name\').focus();
            }
        });
      }',
      'buttons' => array(
          Yii::t('cms','Zamknij')=>'js:function(){$(this).dialog(\'close\')}',
          Yii::t('cms','Zapisz nową grupę')=>'js:function(){
              jQuery.ajax({
                "url":"'.$this->createUrl('recipient/GroupAdd').'",
                "type":"POST",
                "data":$(\'#AddGroupForm\').serializeArray(),
                "success":function(data){
                  $(\'#addGroupDialog\').html(data);
                }
              })
            }',
          ),
  ),
  ));
?>
<?php $this->endWidget('zii.widgets.jui.CJuiDialog');?>
<?Yii::app()->clientScript->registerScriptFile(Yii::app()->baseUrl . '/js/helpers.js');?>
<?$js = 'function reInstall(){GroupsToSelectWhileRecipientsImport(\''.$this->createUrl('newsletter/GroupsToSelectWhileRecipientsImport').'\','.json_encode($groups).')}';?>
<?Yii::app()->clientScript->registerScript('search',$js.'reInstall();')?>

protected/views/recipient/addGroup.php
<? $form = $this->beginWidget('CActiveForm',array('id'=>'AddGroupForm', 'action'=>$this->createUrl('recipient/GroupAdd'))); ?>
<div class="form">
  <?= $this->renderPartial('//shared/_flash')?>
  <?= $form->errorSummary($group)?>
  <div class="row">
		<?= $form->labelEx($group,'name'); ?>
    <?= $form->textField($group,'name')?>
		<?= $form->error($group,'name'); ?>
	</div>
  <input type="submit" name="save" value="save" onclick="return false;" style="display: none" />
</div>
<? $this->endWidget(); ?>

protected/views/recipient/groupEdit.php
<?= $this->renderPartial('//shared/_flash')?>
<div class="form">
  <?php $form=$this->beginWidget('CActiveForm', array('id'=>'GroupEditForm','action'=>$this->createUrl('recipient/groupEdit',array('id'=>$group->id)))); ?>
    <?= $form->errorSummary($group); ?>
    <div class="row">
      <?= $form->labelEx($group,'name'); ?>
      <?= $form->textField($group,'name',array('size'=>60,'maxlength'=>128)); ?>
      <?= $form->error($group,'name'); ?>
    </div>
  <?php $this->endWidget(); ?>
</div>

protected/views/recipient/groups.php
<div class="click_here">
	<?= CHtml::link(Yii::t('cms', 'Kliknij tutaj'),'#addGroup',array('onclick'=>'$(\'#AddGroup\').dialog(\'open\')')) ?> 
</div>
<div class="to_add">
	aby dodać nową grupę.
</div>

<?

$this->widget('zii.widgets.grid.CGridView', array(
    'id' => 'groups-grid',
    'dataProvider' => $group->search(),
    'cssFile' => Yii::app()->theme->baseUrl.'/css/gridview/gridview.css',
    'enablePagination'=> false,
    'columns' => array(
        'name',
        'recipientsActiveCount',
        'recipientsInActiveCount',
//        array(
//            'name'=>  Yii::t('cms', 'Usuń odbiorców'),
//            'value'=>'"<a href=\"\">wyczyść</a>"',
//            'htmlOptions'=>array('onclick'=>'if(confirm("Czy jesteś pewien że chcesz usunąć odbiorców z wybranej grupy?"))','style'=>'padding-right: 10px; padding-left: 0px !important;text-align: right'),
//            'type'=>'html',
//            'filter'=>false
//        ),
        array(
            'class' => 'CButtonColumn',
            'template' => '{update}',
            'header'=>  Yii::t('cms', 'Edycja'),
            'buttons' => array(
                'update' => array(
                    'label'=>  Yii::t('cms', 'Edycja'),
                    'url' => 'Yii::app()->createUrl("recipient/groupEdit", array("id"=>$data->id))',
                    'click' => "function() {
                      $.ajax({
                        'url': $(this).attr('href'),
                        success: function(data) {
                          $('#GroupEdit').html(data);
                          $('#GroupEdit').dialog('open');
                        }
                      })
                      return false;}",
                ),
            )
        ),
    ),
));
?>

<?$this->beginWidget('zii.widgets.jui.CJuiDialog', array('id'=>'AddGroup','options'=>array(
    'autoOpen'=>false,
    'title'=>  Yii::t('cms', 'Dodaj nową grupę'),
    'modal'=>true,
    'width'=>'auto',
    'close'=>'js:function(){$.fn.yiiGridView.update(\'groups-grid\');}',
    'open'=>'js:function(){
      $.ajax({
            \'url\': \''.$this->createUrl('recipient/groupAdd').'\',
            success: function(data) {
              $(\'#AddGroup\').html(data);
            }
          })
    }',
    'buttons'=>array(
        Yii::t('cms', 'Zamknij')=>'js:function(){$(this).dialog("close")}',
        Yii::t('cms', 'Zapisz')=>'js:function(){
          $.ajax({
            \'url\': $(\'#AddGroupForm\').attr(\'action\'),
            \'type\':\'post\',
            \'data\':$(\'#AddGroupForm\').serializeArray(),
            success: function(data) {
              $(\'#AddGroup\').html(data);
            }
          })
          }',
        )
    ))
);
$this->endWidget('zii.widgets.jui.CJuiDialog');?>

<?$this->beginWidget('zii.widgets.jui.CJuiDialog', array('id'=>'GroupEdit','options'=>array(
    'autoOpen'=>false,
    'title'=>  Yii::t('cms', 'Edycja grupy odbiorców'),
    'modal'=>true,
    'width'=>'auto',
    'close'=>'js:function(){$.fn.yiiGridView.update(\'groups-grid\');}',
    'buttons'=>array(
        Yii::t('cms', 'Zamknij')=>'js:function(){$(this).dialog("close")}',
        Yii::t('cms', 'Zapisz zmiany')=>'js:function(){
          $.ajax({
            \'url\': $(\'#GroupEditForm\').attr(\'action\'),
            \'type\':\'post\',
            \'data\':$(\'#GroupEditForm\').serializeArray(),
            success: function(data) {
              $(\'#GroupEdit\').html(data);
            }
          })
          }',
        )
    ))
);
$this->endWidget('zii.widgets.jui.CJuiDialog');?>

protected/views/recipient/index.php
<?

$this->widget('zii.widgets.grid.CGridView', array(
    'id' => 'recipients-grid',
    'dataProvider' => $recipient->search($group->id),
    'cssFile' => Yii::app()->theme->baseUrl.'/css/gridview/gridview.css',
    'filter' => $recipient,
    'columns' => array(
        'email',
        array(
            'name'=>  Yii::t('cms', 'Grupy'),
            'value'=>'implode(\', \',CHtml::listData($data->groups,\'id\',\'name\'))',
            'filter'=>  CHtml::activeDropDownList($group, 'id', array(''=>'')+CHtml::listData(Group::model()->findAll(), 'id', 'name'))
        ),
        array(
            'name'=>'status',
            'value'=>'$data->TranslateEnumValue(\'status\')',
            'filter'=>  CHtml::activeDropDownList($recipient, 'status', array(''=>'')+ZHtml::enumItem($recipient, 'status'))
        ),
        array(
            'class' => 'CButtonColumn',
            'template' => '{update}',
            'header'=>  Yii::t('cms', 'Edytuj'),
            'buttons' => array(
                'update' => array(
                    'label'=>  Yii::t('cms', 'Edytuj'),
                    'url' => 'Yii::app()->createUrl("recipient/view", array("id"=>$data->id))',
                    'click' => "function() {
                      $.ajax({
                        'url': $(this).attr('href'),
                        success: function(data) {
                          $('#RecipientView').html(data);
                          $('#RecipientView').dialog('open');
                        }
                      })
                      return false;}",
                ),
            )
        ),
    ),
));
?>

<?$this->beginWidget('zii.widgets.jui.CJuiDialog', array('id'=>'RecipientView','options'=>array(
    'autoOpen'=>false,
    'title'=>  Yii::t('cms', 'Karta odbiorcy'),
    'modal'=>true,
    'width'=>'auto',
    'close'=>'js:function(){$.fn.yiiGridView.update(\'recipients-grid\');}',
    'buttons'=>array(
        Yii::t('cms', 'Zamknij')=>'js:function(){$(this).dialog("close")}',
        Yii::t('cms', 'Zapisz zmiany')=>'js:function(){
          $.ajax({
            \'url\': $(\'#RecipientViewForm\').attr(\'action\'),
            \'type\':\'post\',
            \'data\':$(\'#RecipientViewForm\').serializeArray(),
            success: function(data) {
              $(\'#RecipientView\').html(data);
            }
          })
          }',
        )
    ))
);
$this->endWidget('zii.widgets.jui.CJuiDialog');?>

protected/views/recipient/tabs.php
<?$this->renderPartial('../shared/_breadcrumbs', array('page' => $page));?>
<?$this->breadcrumbs = array_merge(
        $this->breadcrumbs,
        array(Yii::t('cms', 'Panel zarządzania odbiorcami')=>$this->createUrl('recipient/index',array('page_id'=>$page->id))),
        array($this->pageTitle)
        );?>
<?
$this->widget('CTabView', array(
    'tabs' => $tabs,
    'cssFile' => Yii::app()->theme->baseUrl.'/css/jquery.yiitab.css',
    'activeTab'=>Yii::app()->getController()->action->id,
    'viewData'=>  isset($additionalParams)? array_merge($additionalParams,array('model'=>$model)):array('model'=>$model)
))
?>

protected/views/recipient/view.php
<?= $this->renderPartial('//shared/_flash')?>
<div class="form">
  <?php $form=$this->beginWidget('CActiveForm', array('id'=>'RecipientViewForm','action'=>$this->createUrl('recipient/view',array('id'=>$recipient->id)))); ?>
    <?= $form->errorSummary($recipient); ?>
    <div class="row">
      <?= $form->labelEx($recipient,'email'); ?>
      <?= $form->textField($recipient,'email',array('size'=>60,'maxlength'=>128)); ?>
      <?= $form->error($recipient,'email'); ?>
    </div>
    <div class="row">
      <?= $form->labelEx($recipient,'status'); ?>
      <?= ZHtml::enumDropDownList($recipient, 'status') ?>
      <?= $form->error($recipient,'status'); ?>
    </div>
  <fieldset>
    <legend><?= Yii::t('cms', 'Grupy do których należy odbiorca') ?></legend>
    <?foreach(Group::model()->findAll() as $group):?>
      <?$id = 'group_'.$group->id?>
      <span style="white-space: nowrap; margin-right: 10px">
        <label for="<?= $id?>" style="white-space:nowrap;">
          <input type="checkbox" name="groups[]" id="<?=$id?>" value="<?= $group->id?>"<?if(in_array($group->id, $recipient_groups)):?>checked="checked"<?endif?> /> - <?= $group->name?>
        </label>
      </span>
    <?endforeach?>
  </fieldset>
  <?php $this->endWidget(); ?>
</div>